title: "AgentIQS Documentation"
description: "Complete documentation for AgentIQS platform"

sections:
  - id: "getting-started"
    title: "Getting Started"
    description: "Quick start guide and tutorials"
    pages:
      - id: "quickstart"
        title: "Quick Start"
        file: "sections/getting-started/quickstart.md"
      - id: "test-duplicates"
        title: "Test Duplicates"
        file: "sections/getting-started/test-duplicates.md"

  - id: "concepts"
    title: "Core Concepts"
    description: "Fundamental concepts and principles"
    pages:
      - id: "intro"
        title: "Introduction"
        file: "sections/concepts/intro.md"

  - id: "python-sdk"
    title: "Python SDK"
    description: "Python SDK documentation and reference"
    pages:
      - id: "index"
        title: "Getting Started"
        file: "sections/python-sdk/index.md"
      - id: "classes"
        title: "API Reference"
        file: "sections/python-sdk/classes.md"

navigation:
  showSectionNumbers: true
  showPageNumbers: true
  collapsible: true

theme:
  highlightLanguage: "python"
  showTableOfContents: true
  maxTocDepth: 3
